[[news]]
date = "2026-06"
content = "Started internship at Bitmain as Digital Design & Verification Engineer in Shanghai"

[[news]]
date = "2026-01"
content = "Started FPGA/ASIC design internship at Techhill Technology in Hong Kong"

[[news]]
date = "2025-10"
content = "Joined Qianxin Technology as FPGA AI Acceleration Assistant Engineer in Shenzhen"

[[news]]
date = "2025-09"
content = "Started MSc in Electrical and Computer Engineering (ECE) at The University of Hong Kong"

[[news]]
date = "2025-06"
content = "Graduated from Beijing Jiaotong University with BEng in Communication Engineering"
